/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
 // #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//#include "stm32f4xx.h"

#define SIZE 5
int sumdata=90;
// Function prototypes
int sumArray(int arr[], int size);
int findMax(int arr[], int size);
void processData(int arr[], int size);

int main(void)
{
    int data[SIZE] = {10, 20, 30, 40, 50};
    int sum = 0;
    int max = 0;

    sum = sumArray(data, SIZE);     // 🔴 Breakpoint 1
    max = findMax(data, SIZE);
                                   // 🔴 Breakpoint 2

    processData(data, SIZE);        // 🔴 Breakpoint 3

    while (1)
    {
        // infinite loop
    }
}

// Function to calculate sum
int sumArray(int arr[], int size)
{
    int sum = 0;
    for (int i = 0; i < size; i++)   // ❗ BUG: should be i < size
    {
        sum += arr[i];
    }


    return sum;
}

// Function to find max value
int findMax(int arr[], int size)
{
    int max = arr[0];

    for (int i = 1; i < size; i++)
    {
        if (arr[i] > max)
        {
            max = arr[i];
        }
    }

    return max;
}

// Function to modify array
void processData(int arr[], int size)
{
    for (int i = 0; i < size; i++)
    {
        arr[i] = arr[i] * 2;
    }
}
